version: '3.8'

services:
  pos-terminal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pos_terminal_app
    ports:
      - "8080:80"
    environment:
      - API_URL=http://localhost:5173/api
    restart: always
